export const Logos = {
  INDIAN_FLAG: require('../../Assets/Logos/India_Flag.png'),
  DROPDOWN_ICON: require('../../Assets/Logos/DropdownIcon.png'),
  WHATSAPP_ICON: require('../../Assets/Logos/WhatsappIcon.png'),
  CHEVRON_LEFT_ICON: require('../../Assets/Logos/CHEVRON_LEFT_ICON.png'),
  VERIFY_OTP_EDIT: require('../../Assets/Logos/Verify_OTP_Edit.png'),
  MESSAGES: require('../../Assets/Logos/Messages.png'),
  Input_DropDown: require('../../Assets/Logos/Input_DropDown.png'),


  // RESIDENTIAL_ICON: require('../Assets/Logos/ResidentialIcon.svg'),
  // COMMERCIAL_ICON: require('../Assets/Logos/CommercialIcon.svg'),
  // CARS_ICON: require('../Assets/Logos/CarsIcon.svg'),
  // TWO_WHEELER_ICON: require('../Assets/Logos/TwoWheelerIcon.svg'),
  // SEARCH_ICON: require('../Assets/Logos/SearchIcon.svg'),
  // CHEVRON_DOWN_ICON: require('../Assets/Logos/ChevronDownIcon.svg'),
  // ADD_ICON: require('../Assets/Logos/AddIcon.svg'),
  // LOCATION_ICON: require('../Assets/Logos/LocationIcon.svg'),
  // FAVOURITE_ICON: require('../Assets/Logos/FavouriteIcon.svg'),
  // DOT_DIVIDER: require('../Assets/Logos/DotDivider.svg'),
  // HOME_ICON_ACTIVE: require('../Assets/Logos/HomeIconActive.svg'),
  // HOME_ICON_INACTIVE: require('../Assets/Logos/HomeIconInactive.svg'),
  // MESSAGE_ICON_ACTIVE: require('../Assets/Logos/MessageIconActive.svg'),
  // MESSAGE_ICON_INACTIVE: require('../Assets/Logos/MessageIconInactive.svg'),
  // ADD_LISTING_ICON: require('../Assets/Logos/AddListingIcon.svg'),
  // SAVED_ICON_ACTIVE: require('../Assets/Logos/SavedIconActive.svg'),
  // SAVED_ICON_INACTIVE: require('../Assets/Logos/SavedIconInactive.svg'),
  // PROFILE_ICON_ACTIVE: require('../Assets/Logos/ProfileIconActive.svg'),
  // PROFILE_ICON_INACTIVE: require('../Assets/Logos/ProfileIconInactive.svg'),
  // PRICING_INSIGHTS_ICON: require('../Assets/Logos/PricingInsightsIcon.svg'),
  // EMI_CALCULATOR_ICON: require('../Assets/Logos/EMICalculatorIcon.svg'),
  // RESEARCH_SNAPSHOT_ICON: require('../Assets/Logos/ResearchSnapshotIcon.svg'),
  // LOCALITY_INSIGHTS_ICON: require('../Assets/Logos/LocalityInsightsIcon.svg'),
  RESIDENTIAL_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  COMMERCIAL_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  CARS_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  TWO_WHEELER_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  SEARCH_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  CHEVRON_DOWN_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  ADD_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  LOCATION_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  FAVOURITE_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  DOT_DIVIDER: require('../../Assets/Logos/Input_DropDown.png'),

  HOME_ICON_ACTIVE: require('../../Assets/Logos/Input_DropDown.png'),
  HOME_ICON_INACTIVE: require('../../Assets/Logos/Input_DropDown.png'),

  MESSAGE_ICON_ACTIVE: require('../../Assets/Logos/Input_DropDown.png'),
  MESSAGE_ICON_INACTIVE: require('../../Assets/Logos/Input_DropDown.png'),

  ADD_LISTING_ICON: require('../../Assets/Logos/Input_DropDown.png'),

  SAVED_ICON_ACTIVE: require('../../Assets/Logos/Input_DropDown.png'),
  SAVED_ICON_INACTIVE: require('../../Assets/Logos/Input_DropDown.png'),

  PROFILE_ICON_ACTIVE: require('../../Assets/Logos/Input_DropDown.png'),
  PROFILE_ICON_INACTIVE: require('../../Assets/Logos/Input_DropDown.png'),

  PRICING_INSIGHTS_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  EMI_CALCULATOR_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  RESEARCH_SNAPSHOT_ICON: require('../../Assets/Logos/Input_DropDown.png'),
  LOCALITY_INSIGHTS_ICON: require('../../Assets/Logos/Input_DropDown.png'),

};