export const Strings = {
  ONBOARDING: {
    LOGIN: 'Log in',
    CREATE_ACCOUNT: 'Create Account',
    SLIDES: [
      {
        HEADING: 'Find Your Dream Home',
        DESCRIPTION: 'Discover a wide range of residential properties tailored to your lifestyle.',
      },
      {
        HEADING: 'Business spaces for you',
        DESCRIPTION: 'Browse premium commercial spaces designed for success in your business.',
      },
      {
        HEADING: 'Drive with Confidence',
        DESCRIPTION: 'Shop certified, pre-owned cars offering reliability and great value.',
      },
      {
        HEADING: 'Ride in Style',
        DESCRIPTION: 'Find high-performance motorcycles designed for enthusiasts and thrill-seekers.',
      },
    ],
  },
  LOGIN: {
    LOGO_TEXT: 'MD',
    LANGUAGE: 'EN',
    HEADING: "What's your mobile number?",
    SUBHEADING: "We'll send an OTP to verify your number.",
    COUNTRY_CODE: '+91',
    INPUT_PLACEHOLDER: 'Enter your mobile number',
    BUTTON_NEXT: 'Next',
    DIVIDER_TEXT: 'or',
    WHATSAPP_BUTTON: 'Continue with Whatsapp',
    DISCLAIMER: 'By registering,  you agree to receive calls or messages via SMS or WhatsApp for verification and service updates from MagicDwell and its partners.',
    ERROR_PHONE_REQUIRED: 'Phone number is required',
    ERROR_PHONE_INVALID: 'Please enter a valid 10-digit mobile number',
  },
  VERIFY_OTP: {
    SCREEN_TITLE: 'Verify OTP',
    HEADING: 'Enter verification code',
    SENT_TO_PREFIX: 'Sent to ',
    BUTTON_VERIFY: 'Verify',
    RESEND_PREFIX: 'Resend in ',
    RESEND_SUFFIX: '15s',
  },
  ACCOUNT_DETAILS: {
    SCREEN_TITLE: 'Your Account Details',
    NAME_LABEL: 'Name',
    NAME_PLACEHOLDER: 'Enter name',
    EMAIL_LABEL: 'Email address (optional)',
    EMAIL_PLACEHOLDER: 'Enter email address',
    CITY_LABEL: 'Preferred City',
    CITY_PLACEHOLDER: 'Select city',
    TERMS_PREFIX: 'I agree to the ',
    TERMS_OF_SERVICE: 'Terms of Service',
    TERMS_AND: ' and ',
    PRIVACY_POLICY: 'Privacy Policy',
    BUTTON_CONTINUE: 'Continue',
  },
  HOME: {
    CURRENT_LOCATION: 'Current location',
    POST_A_LISTING: 'Post a Listing',
    SEARCH_PLACEHOLDER: 'Search landmark, locality, project...',
    CATEGORIES: 'Categories',
    NEWLY_ADDED_PROPERTIES: 'Newly-added properties for Sale',
    TOOLS_INSIGHTS: 'Tools & Insights',
  },
  CATEGORIES: {
    RESIDENTIAL: 'Residential',
    COMMERCIAL: 'Commercial',
    CARS: 'Cars',
    TWO_WHEELER: 'Two-wheeler',
    APARTMENTS: 'Apartments',
    BUILDER_FLOORS: 'Builder Floors',
    PLOTS_LAND: 'Plots / Land',
    VILLAS: 'Villas',
    CO_LIVING: 'Co-living',
  },
  TOOLS: {
    PRICING_INSIGHTS: 'Pricing &\\nInsights',
    EMI_CALCULATOR: 'EMI\\nCalculator',
    RESEARCH_SNAPSHOT: 'Research\\nSnapshot',
    LOCALITY_INSIGHTS: 'Locality\\nInsights',
  },
  TABS: {
    HOME: 'Home',
    MESSAGES: 'Messages',
    SAVED: 'Saved',
    PROFILE: 'Profile',
  },
  POST_LISTING: {
    TITLE: 'Post a listing for',
    PROPERTY: 'Property',
    VEHICLE: 'Vehicle',
    CONTINUE: 'Continue',
  },
  PROPERTY_LISTING: {
    SCREEN_TITLE: 'Post property',
    PROPERTY_TYPE: 'Property type',
    LOOKING_TO: 'Looking to',
    ADD_LOCATION: 'Add location',
    SEARCH_LOCATION: 'Search location',
    LOCATE_MY_LOCATION: 'Locate my location',
    CATEGORY: 'Category',
    BUILDING_NAME: 'Building/Project/Society name',
    LOCALITY: 'Locality',
    TOTAL_FLOORS: 'Total floors',
    YOUR_FLOOR: 'Your floor',
    BHK_TYPE: 'BHK type',
    BUILT_UP_AREA: 'Built up area',
    FURNISH_TYPE: 'Furnish type',
    CONSTRUCTION_STATUS: 'Construction status',
    PROPERTY_AMENITIES: 'Property amenities',
    VIEW_ALL: 'View all',
    ADD_PHOTOS: 'Add photos',
    COST: 'Cost',
    AGE_OF_PROPERTY: 'Age of property (in years)',
    ATTACH_DOCUMENT: 'Attach document',
    SELECT_AMENITIES: 'Select amenities',
    NOT_IN_LIST: 'Not in the list? Add yours',
    BACK: 'Back',
    CONTINUE: 'Continue',
    PREVIEW_AND_PUBLISH: 'Preview & Publish',
    PUBLISH_POSTING: 'Publish posting',
    LISTING_PREVIEW: 'Listing preview',
    VIEW_ALL_DETAILS: 'View all details',
    VIEW_ALL_AMENITIES: 'View all amenities',
    PROJECT_OVERVIEW: 'Project overview',
    NEARBY_PROPERTIES: 'Nearby properties',
  },
};